### ISSUE TITLE
update favicon

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#10]
* currently somebody's face
* does ALAO have a favicon? I don't see one on the site

**Comment by dzoladz** [comment]
lol... that's the favicon from my personal website. I used it so I'd remember - or be reminded 😃 - we need to create a favicon. I do not believe ALAO has a favicon at the moment. There is no favicon at https://www.alaoweb.org/

**Comment by kenirwin** [comment]
I couldn't decide if I thought it looks like you or not -- hard to tell at 32px, but it seemed plausible. I made one, though we might be able to do better if we had access to the original illustrator file.

**Comment by kenirwin** [comment]
Possible improved favicon, but would require approval from whoever is in charge of logos and such: 
![favicon-square-32x32](https://user-images.githubusercontent.com/1894561/83309405-28a27f00-a1d7-11ea-9f7b-1eb4e760d7fb.png)
