### ISSUE TITLE
Need Page for Award Winners

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#112]

**Comment by dzoladz** [comment]
Winner may need to be updated in WA and on the conference website

**Comment by kenirwin** [comment]
Notes from Aug 14 CPC meeting:
* Katy M as Past-Pres is in charge of awards. Mandi will work on this with her. 
* May happen early at Membership Meeting
* Maybe presented/recorded in advance, opportunity to get photos in advance

Suggestions for website: 
* build page in advance, maybe with some fill-in-the blank content
* prepare some "ads"/alerts on the website to sprinkle in to drive attention throughout conference

**Comment by dzoladz** [comment]
> Mandi is chatting with me on Wednesday to bounce ideas, but this will be her/CPC’s call.
From Katy Mathuews 8/24/2020

**Comment by dzoladz** [comment]
Awards will be scheduled during the Thursday Lunch: 12:30 - 1:00pm (30 minutes).

Live Zoom announcements w/ a recording that needs to be made available by the evening social event, so a CPC member will need to be involved to ensure the video is available.

**Comment by dzoladz** [comment]
Development will continue using issue #270
