### ISSUE TITLE
Enable Call for Proposals Function

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#12]
I just received the link for the re-opened call for proposals.

https://docs.google.com/forms/d/e/1FAIpQLSdfGZEuGcn_KmpEqd9-GgU-xPWhViP1bivXOvJKcEvJ1DtLFw/viewform?usp=sf_link

Enabling the call for proposals should only require that the `c4pUrl` variable in `_config.yml` be updated with the CFP link. At the moment, I believe the CFP link only displays on the `/speakers` page. We might want to consider other locations to solicit proposals.

**Comment by kenirwin** [comment]
What is the likelihood that we'll launch the conference website before the CFP closes June 26? For this year, will it matter much if we get this one done?

**Comment by dzoladz** [comment]
For this year, I don't think it matters. I'd suggest that we target a switch to this conference website at the close of this year's CFP... just to set a target using an understandable cutover date.

Other thoughts?
