### ISSUE TITLE
Description Fields in `sessions.yml` Contain Redactions

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#145]
I noticed that several of the description fields in `sessions.yml` contain redactions. For example:
```bash
[institution name]
[Project Title]
[INSTITUTION NAME]
```

These redactions were added to facilitate the proposal review process. We'll need to update `sessions.yml` with the original information before we publicize the sessions on the conference site.

**Comment by dzoladz** [comment]
@kenirwin Do we have the originally submitted proposal descriptions available to us?

**Comment by kenirwin** [comment]
@dzoladz - I've just shared the unredacted version with you via GDrive

**Comment by Walton485** [comment]
I've removed the redactions, and we should be all set

**Comment by dzoladz** [comment]
Closing, per @Walton485
