### ISSUE TITLE
Alphabetically Sort Speaker Cards by Last Name

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#153]
I've received a several email about the speaker images being 'out of order'. I think librarians anticipate being able to skim the list of speakers alphabetically by last name. I'm in favor of implementing this sorting behavior, but I'm opening this issue for discussion within the team.

**Comment by kenirwin** [comment]
I notice that Jillian Ewalt sorts to the bottom of the list of speakers. Does she have a funny character that causes her to sort oddly?

**Comment by dzoladz** [comment]
@kenirwin Hmm... maybe? I'll have to take a look this evening

**Comment by kenirwin** [comment]
I think see what's happening -- I thought PR #155 had been merged already and wasn't working. It looks like it's working fine.
