### ISSUE TITLE
need Dress for Success charity/promotion page

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#154]
expect email from Allen R with details

**Comment by dzoladz** [comment]
I've had a quick back-and-forth with Marsha and Allen. After the initial email exchange, I'm going to explore how best to facilitate donations for those included to do so.

**Comment by dzoladz** [comment]
Wireframe
![image001](https://user-images.githubusercontent.com/10561752/90986974-28efb380-e555-11ea-9faa-a641ffedc298.png)
