### ISSUE TITLE
sort featured speakers to top of speakers page? 

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#159]
Previously we had our rockstar speakers sorted to the top of the page by virtue of being the first ones in the list. Do we want to have a "featured speakers" section at the top with the four of them, and then a separate list of hoi polloi?

**Comment by dzoladz** [comment]
I'm inclined to only "feature" the featured speakers on the main conference page, preferring to retain the alphabetical list on the speakers page itself.

What do others think?

**Comment by dzoladz** [comment]
Hi, All -

Please take a look at the deploy preview of Ken's proposal and provide any feedback or comments
https://deploy-preview-162--alao-production.netlify.app/speakers/

**Comment by dzoladz** [comment]
Closing... Team decided that featured speakers should be sorted to the top with larger images
