### ISSUE TITLE
List of Presenters in Poster Modals Accumulate on Search Search Interface 

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#161]
On the Session Search interface, the list of presenters in the "About the Presenter(s)" of a poster modals is not accurate. The names of poster presenters accumulate as you view models further down the list, irrespective of the author of the poster session.

For example,
- https://2020.alaoweb.org/session-search/#poster-posterswork-from-home (displays single presenter)
- https://2020.alaoweb.org/session-search/#poster-postersalumni-engagement (displays all poster presenters)

**Comment by kenirwin** [comment]
@dzoladz - I'm unable to replicate this. Will you please attach a screenshot to show me what you're seeing? Thanks!

**Comment by kenirwin** [comment]
@dzoladz -ok, i think I found the error you're seeing. I'll work on that this afternoon.

**Comment by dzoladz** [comment]
Here's a screenshot. Poster modals are showing presenters not affiliated with the specific poster.

<img width="816" alt="Screen Shot 2020-08-18 at 11 27 40 AM" src="https://user-images.githubusercontent.com/10561752/90533103-05d49680-e146-11ea-8839-0163f98bfcef.png">
