### ISSUE TITLE
possible further favicon improvements

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#18]
I worked up a square version of the ALAO logo; I presume it'd need approval from ALAO's logo czar (do we have a logo czar? maybe the publicity chair?) 
![favicon-square-32x32](https://user-images.githubusercontent.com/1894561/83309445-48d23e00-a1d7-11ea-95f0-893ba898f179.png)

**Comment by kenirwin** [comment]
Because favicons are square, the rectangular shape of "alao" squishes down a lot and is hard to read. The square logo will be a better use of space, but loses a bit of our traditional branding. I present this as an option to be modified, discarded, or whatever.

**Comment by dzoladz** [comment]
As a square logo, I'm not sure how I'm to read the letters. @Nassaubound or @hillmk1 would have a better idea who to contact, as they recently completed the redesign of ALAO's website.

**Comment by kenirwin** [comment]
@dzoladz - here's another draft of a square-layout, using the horizontal offset to hopefully make the reading order clear: 
![favicon-32x32](https://user-images.githubusercontent.com/1894561/83523228-dc459080-a4af-11ea-9387-230c6a20debd.png)

What do you think of this one?

**Comment by dzoladz** [comment]
I think the horizontal offset makes it more clear. Let's go ahead and use it. If someone complains, we can switch back to the earlier version. I'll assign this one to you, just to make it clear that you're leading the work on the update.
