### ISSUE TITLE
Subscribe to ALAO Mailing List Does Not Work

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#19]
At the moment, there is no target mailing list set up for the subscribe function on the website. It needs to be configured to route subscription requests to ALAO's Google Group.

**Comment by Nassaubound** [comment]
Which group do we want to use? Do we want to create a new one?

**Comment by dzoladz** [comment]
Is it possible to use this one?

The ALAO Discussion List, list@alaoweb.org, is hosted on Google.

**Comment by Nassaubound** [comment]
I guess I don't understand what this is for. I thought it was a conference mailing list.

**Comment by dzoladz** [comment]
@Nassaubound My thought was that this tool could be used to add folks to the general ALAO mailing list. We tend to make conference announcement over the general list... and to the folks who only attend the annual conference, this might facilitate a broader awareness of ALAO activities more generally.

**Comment by dzoladz** [comment]
Rather than fussing with Google APIs, I'm going to investigate another option of using a third-party service, as as MailChimp. We could use it to: (1) collect email address of folks who would like to be subscribed to ALAO's mailing list, (2) export those contacts from MailChimp, and (3) batch subscribe those email addresses to the Google Group for ALAO's mailing list.
