### ISSUE TITLE
Add time/date info to session modal? 

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#205]
Currently, the modal info for presentations doesn't include their presentation and/or Q&A time; should we add that to the layout?

**Comment by dzoladz** [comment]
There's a value in `sessions.yml` to hold the Q&A time
```bash
  live-stream-type: Q&A
  live-stream-time: "2020-10-28 15:30:00"
  live-stream-link: "https://www.example.com"
```
The modal template has already been taught how to handle those values. Right now, there's only one sessions that's using it: https://2020.alaoweb.org/schedule/#session-3. We just need to populate the other times.

Can you open a distinct issue for populating the Q&A times? I think that's something that @Nassaubound or @Walton485 could easily take care of for the team.

**Comment by dzoladz** [comment]
@Nassaubound is going to add these values using [GitHub's built-in editing features](https://docs.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository) to resolve issue #207 

@kenirwin can we close this issue?
