### ISSUE TITLE
Add live-stream-time values in data/sessions

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#207]
We need to add `live-stream-time` values in the _data/sessions.yml file, e.g.:
```
live-stream-type: Q&A
live-stream-time: "2020-10-28 15:30:00"
```

I believe we know now when these times are.

**Comment by dzoladz** [comment]
We'll need to calculate the exact times, but my understanding is that the Q&A is simply the last time minutes of the hour session.
