### ISSUE TITLE
New front page image

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#21]
* do we have a stash of conference images suitable for use?

**Comment by dzoladz** [comment]
I'm not aware of an image archive, but @Nassaubound or @hillmk1 might know.

Since I wanted to give the conference site the feel of the physical environment of the most recent conference location (i.e. Nationwide), I pulled public photos from ALAO's Twitter and Facebook accounts.

**Comment by hillmk1** [comment]
There are several files in Google Drive at https://drive.google.com/drive/folders/1laq5NJ2DkKAKST0PlRGOkZslyMm-Rkbx?usp=sharing. Is this a situation where I should learn how to add images in github?

**Comment by Nassaubound** [comment]
There are also some images in WA and the wayback machine from past conferences, but I'm not sure it's what you're looking for.  I have 2 copies of our old Picasa collection, but they are both at the office. The issue of ALAO event photographs and archiving has been discussed at recent board meetings, but it's still active. Are the public photos sufficient or should I look deeper?

**Comment by hillmk1** [comment]
Oh! Last night I was thinking of conference logos, not photos. Right, there are plenty in WA. Ken, do you have access there? Do we need more than what you two already have?

**Comment by kenirwin** [comment]
@hillmk1 - I don't think I have any special access in WA

**Comment by hillmk1** [comment]
Hey Ken, I've given you some permissions in Wild Apricot. I dug a little more, though, and while we do have a lot of images stored there, there aren't a lot of images from conferences. We might ask about it during the CPC meeting. Perhaps Melissa Cox Norris (or even Don?) might have more images that we don't have in WA.

**Comment by dzoladz** [comment]
@kenirwin It sounds like additional conference photos will be added to Google Drive... and you've got permissions to review files added to WA.

**Are you willing to lead this issue?** i.e. review the potential images and select one for the conference front page

**Comment by dzoladz** [comment]
Finding a suitable image that adequately represents 'resilience' is proving to be a challenge. I've thought about: (1) organic resilience, a view of seeding and reproduction; (2) objects, a la mechanical resilience; (3) abstract form, an interpretive expression of resilience.

Tossing out a few examples and totally open to other approaches/ideas/images:

1.
<img width="1126" alt="Screen Shot 2020-06-13 at 5 54 07 PM" src="https://user-images.githubusercontent.com/10561752/84582205-394a1c00-adb7-11ea-930d-19aad11f2ab4.png">

2.
<img width="1126" alt="Screen Shot 2020-06-13 at 8 05 16 PM" src="https://user-images.githubusercontent.com/10561752/84582213-46670b00-adb7-11ea-93fd-940c1a4e70d2.png">

3.
<img width="1126" alt="Screen Shot 2020-06-13 at 8 18 34 PM" src="https://user-images.githubusercontent.com/10561752/84582218-52eb6380-adb7-11ea-9ef4-8473dad59d90.png">

**Comment by kenirwin** [comment]
@dzoladz - I like the ideas you posted on non-ALAO-specific/resilience-oriented images. I'll see what else I can find. (I think the spring is a clear visual idea, but a hard background to work with, so maybe a different spring could work.)

**Comment by kenirwin** [comment]
Some more possibilities:

<img width="1363" alt="Screen Shot 2020-06-15 at 3 05 26 PM" src="https://user-images.githubusercontent.com/1894561/84696259-387dcb00-af1a-11ea-8ddf-982adfaa3419.png">
![Uploading Screen Shot 2020-06-15 at 2.45.19 PM.png…](
<img width="1343" alt="Screen Shot 2020-06-15 at 11 44 21 AM" src="https://user-images.githubusercontent.com/1894561/84696265-3c115200-af1a-11ea-8ae5-88cbae9a07b3.png">
<img width="1350" alt="Screen Shot 2020-06-15 at 11 43 10 AM" src="https://user-images.githubusercontent.com/1894561/84696266-3ca9e880-af1a-11ea-983a-87e84b666e17.png">

**Comment by kenirwin** [comment]
<img width="1337" alt="Screen Shot 2020-06-15 at 4 27 04 PM" src="https://user-images.githubusercontent.com/1894561/84702770-2a817780-af25-11ea-96d7-79ca0315a491.png">

**Comment by dzoladz** [comment]
I'm going to put a block on this topic for the moment.

Over this past weekend, I sent an email to the CPC chair about our progress and about our uncertainty with the retention of the toppling books iconography within a design that favors full section backgrounds. I do not want us to get bogged down rewriting a ton of CSS and template structure for a single image.

I just heard back and there's concern about losing the original conference branding. While I don't read 'books toppling over like dominos' as a representation of 'resilience', I can understand the need to retain a consistent message with the branding for this conference cycle.

I'll see if we can possibly get an SVG that would retain its crispness across multiple form factors. If so, I think we could simply replace the background with an SVG and remove a few strings from `_config.yml`.

**Comment by dzoladz** [comment]
One of the challenges is striking a balance between designing a conference site that minimizes any unnecessary complexity in favor of a reusable product and maximizing customizations to meet the needs of a single conference. At every decision point, I’m leaning towards the former.

I am able to drop the SVG into the landing page without too much difficulty and minimizing the JavaScript and CSS modifications of the codebase. But there are some compromises to this approach. Perhaps the biggest UX compromise would be eliminating the top-level navigation on page load.

At the moment, this is too much of a compromise in my eyes.

The original site’s functionality was architected around a set of design expectations that included a site landing page with a dark background image.

I've asked for another SVG with white lettering that we could potentially incorporate to get the best of both worlds.

**Comment by dzoladz** [comment]
Here's a quick draft that I sent back to the CPC chair yesterday evening:

<img width="946" alt="Screen Shot 2020-06-17 at 9 21 53 PM" src="https://user-images.githubusercontent.com/10561752/85016993-bf0ff380-b138-11ea-9c01-ad729bd2e919.png">

**Comment by dzoladz** [comment]
The CPC Chair wants to use a landing page similar to the above. I'll create a branch of code and open a PR shortly.
