### ISSUE TITLE
Give the Team a 🙌

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#216]
![Seattle Mariners baseball player running into the dugout to celebrate with his teammates](https://media.giphy.com/media/7PRK6sEWxcZvq/source.gif)

**Comment by kenirwin** [comment]
nice =)

**Comment by hillmk1** [comment]
That doesn't look like six feet.

**Comment by kenirwin** [comment]
@hillmk1 - something I've learned in the last 6 months is that people are really bad at understanding how far away 6' is...
