### ISSUE TITLE
Switch from Early Bird to Regular Registration on September 28th

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#222]
Early bird registration is only valid through September 27th.

This change should only require two changes within `_config.yml`.

Under `ticketsOffers:`,
- [x] Find `- name: "Early Bird"` and set `disabled: true`
- [x] Find `- name: "Regular Rate"` and set `disabled: false`

**Comment by kenirwin** [comment]
closed with #253 

Sorry @Nassaubound -- I had thought it was assigned to me and had it on my calendar; just now saw that I was wrong!

**Comment by Nassaubound** [comment]
Hey no worries @kenirwin  I was just now looking at it, so I'm glad you were able to make the change. Thanks much!
