### ISSUE TITLE
Add more uses of hashtag throughout site?

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#231]
If we want people to use the hashtag, I suspect it needs to be more visible -- possibly part of the page header or some other prominent spot. What would we think of something like this?
 
<img width="1332" alt="Screen Shot 2020-09-21 at 8 42 12 AM" src="https://user-images.githubusercontent.com/1894561/93767885-8c1d4600-fbe6-11ea-87ed-68aa5017e19b.png">

**Comment by dzoladz** [comment]
I'm fine with that approach. Let's use the hashtag variable set in `_config.yml`
