### ISSUE TITLE
Add 'Join Q&A' Button to Session Modals

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#26]
Adding a button to launch a Zoom meeting Q&A from each session's modal in the conference schedule seems to be the easily way to communicate those Zoom links to conference attendees.

I'm open to other ideas and thoughts on how to be solve the problem of making it easy for conference attendees to join the keynote and Q&A Zoom meetings.

**Comment by dzoladz** [comment]
CPC recommends labeling the Q&A button with something like: "Q&A will begin at {time}"

**Comment by kenirwin** [comment]
@dzoladz - can you point to an example page on the test site? I can't find a detail page -- I was assuming I'd click on a link in the schedule, but I'm not getting anything there. Is that part of the same modal problem you fixed with the posters?

**Comment by dzoladz** [comment]
@kenirwin Here's what I was thinking:

<img width="775" alt="qa_example" src="https://user-images.githubusercontent.com/10561752/84089421-ed653480-a9bc-11ea-845e-e0dd1af3415d.png">

**Comment by kenirwin** [comment]
Thanks -- those modals weren't loading for me yesterday, but they are now. 

Are we going to need to add some data elements to the `sessions.yml` file to support this? Do we need to add a `questions-time` datestamp and then only include the "Launch Q&A" for the relevant items?
