### ISSUE TITLE
some CSS not building to main.css on test site?

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#34]
I noticed that the poster session formatting looks pretty mediocre on the test site (not different font sizes for `.poster-title` etc.). It seems that the `main.css` file that is built on the test site is about 4000 characters shorter than the same file on my localhost. Are there some partials not getting built out on the site? Not sure how to go about checking that. 

See: http://2020.alaoweb.org/css/main.css
search text for "poster" -- there's nothing there.

**Comment by dzoladz** [comment]
> the poster session formatting looks pretty mediocre
I'm considering this a mock-up... just something to get us started. I'd prefer to mimic the typographic styling of the conference sessions. I find those to be fairly clean.

> Are there some partials not getting built out on the site?
Let me know what you find out. I've just added the Emery Pratt logo to master and pushed my `main.css` file along with it. It's possible that I missed adding it to my commits over the weekend, as I didn't make any changes to any of the SCSS partials after pulling master, so `main.css` should not have been available for commit.

**Comment by kenirwin** [comment]
To be clear: I wasn't criticising the layout, just noting that the CSS was clearly missing. 
Whatever the problem was seems to have changed -- the character count in main.css on the site now matches what I'm seeing on localhost. I'm going to close this issue, but if we see future instances of the CSS building incorrectly we may want to hunt down the problem.
