### ISSUE TITLE
Sponsorship Architecture Not Sufficiently Robust

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#40]
I've just been informed of the sponsorship framework for the 2020 conference. Based upon the details of this framework, we'll need to have a discussion on how to best handle adding sponsors.

**Comment by dzoladz** [comment]
As far as sponsorship levels, here's what I have:

![image](https://user-images.githubusercontent.com/10561752/84398564-1b6d9300-abce-11ea-98ca-5e75861dabf5.png)

**Comment by dzoladz** [comment]
One proposal for adding sponsor logos to session modals:

![image](https://user-images.githubusercontent.com/10561752/84398700-435cf680-abce-11ea-8471-1e42b73cc1b6.png)

**Comment by kenirwin** [comment]
I like where you're going with this. I'd want to add some text to the effect of "Session sponsored by: OhioNET" rather than just the logo. I could also image sponsor-level badges, so that the OhioNET logo might get a "Gold Level Sponsor" badge on or next to it.

**Comment by dzoladz** [comment]
I'll start a new branch of code to work on the sponsorship integrations this week.
