### ISSUE TITLE
Missing CPC Team Members

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#5]
There's a an example entry - as well as an empty template data structure - in `/_data/team.yml` to use when adding team members to the site. Be sure to increment the `id:` value when copy/pasting the template to add new members.

Below are the members that need to be added to the `/_data/team.yml` file:

- Don Appleby, University of Akron
- Amanda Black, University of Dayton
- Heather Crozier, Ohio Northern University
- Mark Eddy, Case Western Reserve University
- Mandi Goodsett, Cleveland State University (Chair)
- Melissa Hill, Ohio Wesleyan University
- Ken Irwin, Miami University
- Sara Klink, Stark State College
- Katy Mathuews, Ohio Univeristy
- Stacey McKenna, The Ohio State University
- Marsha Miles, Cleveland State University
- Melissa Cox Norris, University of Cincinnati
- Allen Reichert, Otterbein University
- Ryan Scott, Columbus State Community College
- Shelby Stuart, Case Western Reserve
- Zach Walton, The Ohio State University

**Comment by kenirwin** [comment]
Ken Irwin: ![Ken-Irwin](https://user-images.githubusercontent.com/1894561/83448898-a86f5a00-a420-11ea-9d94-291d8132acfa.jpg)

**Comment by Walton485** [comment]
Zach Walton: ![Zach Walton](https://user-images.githubusercontent.com/65615910/83449397-8c1fed00-a421-11ea-8492-9dacd99a5f94.jpeg)

**Comment by dzoladz** [comment]
@Nassaubound @Walton485 

I've uploaded 6 CPC member photos that I received this morning to the `/img/people` directory of the site. I'll paste the details for the `/_data/team.yml` file below. Keep in mind that you'll need to increment the `id` value by one for every new entity that gets added to any of the data files in the `_data` directory of the site.

```bash
**Stacey McKenna**
Reference and Instruction Librarian
The Ohio State University Newark & Central Ohio Technical College

**Marsha Miles**
title: Head, Collections and Digital Initiatives
site: https://works.bepress.com/marsha_miles/
Michael Schwartz Library
Cleveland State University

**Heather Crozier**
title:     Electronic Resources Librarian, Ohio Northern University
twitter: https://twitter.com/hrcroz

**Ken Irwin**
  id: 1
  name: "Ken"
  surname: "Irwin"
  title: "Web Services Librarian - Miami University"
  thumbnailUrl: 
  team: true
  ribbon:
    - {abbr: "", title: ""}
  social:
    - {name: "twitter", link: "https://twitter.com/irwin_ken"}
    - {name: "github", link: "https://github.com/kenirwin"}
    - {name: "site", link: "https://kenirwin.net"}

**Shelby Stuart, MSI (she/her/hers)**
Electronic Resources Librarian
Personal Librarian for Clarke Residential College
Kelvin Smith Library, Office 201-A
Case Western Reserve University
My title is "Electronic Resources Librarian, Case Western Reserve University"
```

**Comment by Nassaubound** [comment]
Thanks Derek. I was able to load the project to PyCharm and begin updating the file. I will likely need some help to make sure I get the steps done correctly when I'm ready to make an update.

**Comment by dzoladz** [comment]
Sounds good. Before you being to make any changes, you'll want to create a new local branch for those changes to live on. There are a few ways to do it in PyCharm. One is to open the terminal and type something like `git checkout -b issue5`. The other is to click on the branch icon in the lower tool plane in PyCharm and click `+ New Branch`

![New Branch](https://user-images.githubusercontent.com/10561752/83565678-d15d2100-a4ec-11ea-8bc7-a801d0f72a18.png)

**Comment by dzoladz** [comment]
More entries:

```bash
Name: Mandi Goodsett
Title: Performing Arts & Humanities Librarian; OER & Copyright Advisor - Cleveland State University; ALAO Vice President/President-Elect
Twitter: https://twitter.com/mgoodsett1015

Sara Klink
My title is Assistant Director of Library Services at Stark State College
My ALAO role is Instruction Group Coordinator
I don't have a personal bio page but I could do one in LibGuides. Would that work?
```

**Comment by dzoladz** [comment]
A few more:

```bash
Allen Reichart
Title: Electronic Access Librarian - Otterbein University

Melissa Hill
My title is Serials & Electronic Resources Manager  Ohio Wesleyan University.
```

**Comment by Walton485** [comment]
@dzoladz Thanks for reaching out! No help necessary at the moment, Ryan and I both have had kind of an overwhelming week, since the semester started up at his institution, and as a member of the OSU Lima campus diversity committee, I’ve been very involved with some events tied to the recent protests. Today's a quiet day so I'm hoping to make a lot of progress on this issue, but I'll reach out if I need any help!

**Comment by Walton485** [comment]
`
Sara Klink (updated): ![Sara_Klink2](https://user-images.githubusercontent.com/65615910/84413055-1adcf880-abde-11ea-8aeb-5438f32abef3.JPG)
`

**Comment by dzoladz** [comment]
@Walton485 Do you want the above photo to replace the image in the current `/img/people/` directory on the site?

**Comment by Walton485** [comment]
@dzoladz yes, I would really appreciate that! I just thought this image could be touched up a bit when I got to her portion of the issue.

**Comment by dzoladz** [comment]
@Walton485 Done! If you touch up any others, just post them here and I'll know what to do with them next time.

**Comment by dzoladz** [comment]
Closing. Completed by PR #42
