### ISSUE TITLE
Pronoun Display Needs to be Adjusted

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#56]
From Ken:
> the positioning could be better (just to the right of the h2 name by preference, but I couldn't figure that out.

**Comment by kenirwin** [comment]
Also needs better responsive handling, see how pronouns push lastname down on a narrow screen: 
<img width="321" alt="Screen Shot 2020-06-19 at 2 13 43 PM" src="https://user-images.githubusercontent.com/1894561/85167662-2f04a380-b237-11ea-8de8-2476b567fcb9.png">

**Comment by dzoladz** [comment]
@kenirwin Thanks for pointing out the responsive handling. I'll keep that in mind when designing a solution.

**Comment by kenirwin** [comment]
One option is to set the breakpoint to drop from 3 to 2 columns of faces earlier. Another might be to allow more room for the name/pronoun div; I think right now it's 8 columns wide; maybe nine would help while still leaving room for the social links.
