### ISSUE TITLE
Add pronouns for remaining team, presenters

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#57]
### Featured Speakers
* [ ] Rebekkah Smith Aldrich
* [x] Kaetrena Davis Kendrick
* [x] Nancy S. Kirkpatrick

### Committee
* [x] Don Appleby
* [x] Amanda Black
* [x] Mark Eddy
* [x] Melissa Hill
* [x] Sara Klink
* [x] Stacey McKenna
* [x] Marsha Miles
* [x] Melissa Cox Norris
* [x] Allen Reichert
* [x] Ryan Scott
* [x] Shelby Stuart
* [x] Zach Walton
* [x]  Heather Crozier

**Comment by dzoladz** [comment]
An opportunity to capture speaker pronouns during acceptance emails

**Comment by dzoladz** [comment]
@kenirwin Since we have received all but one set of pronouns, are we good to close this issue? I don't think we should expect, nor require, 100% participation.

**Comment by kenirwin** [comment]
Agreed.
