### ISSUE TITLE
Poster Template Lacks Look & Feel of Site

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#63]
The poster session template should better follow the 'look & feel' of other conference site components and pages. It feels a bit disconnected at the moment.

Link to current template:
https://2020.alaoweb.org/posters/author-poster-title

Data for each poster session is in the `_posts` directory. Poster design is in `_layouts/poster.html`

CPC provided the following to guide our design efforts: https://acrl.ala.org/DLS/2020-virtual-poster-session/lets-tell-a-story/

**Comment by dzoladz** [comment]
@dwgreen1 I've additionally assigned myself to this issue, as #64 and in some ways #41, will need to work collaboratively to come up with a uniform solution. I've also added the priority label, as we'll need to have this resolved in the next 3 weeks.

**Comment by kenirwin** [comment]
Part of this reworking should be to make sure that headers are consecutive (h2 below h1, not going straight from h1 to h3). It should also have an h1 title in the hero banner at top, which is currently does not,.

**Comment by dzoladz** [comment]
Updates merged into master from #132 and #135
