### ISSUE TITLE
Session navigation other than schedule grid

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#65]
I believe that right now the only way to find sessions is to look thru the schedule grid. I suggest we ought to have other ways, e.g.: 
* list by title
* maybe list by time & title (more textual, less grid)
* master index of presenters that links or lists both posters and presentations (that one could get into some weird Liquid business, but seems worthwhile.)

**Comment by dzoladz** [comment]
Team suggests using a tabular view with multiple filtering functions.
