### ISSUE TITLE
Schedule of Sessions is Incomplete

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#73]
Session data elements need to be added to `schedule.yml` to complete the interactive conference program.

As this requires CPC input, I'm placing a block on this issue. @Walton485 would like to add this info, so this issue is serving as a placeholder for now.

**Comment by kenirwin** [comment]
Schedule from Mandi:

https://docs.google.com/document/d/1jRUpph7G_PQLBpj-D4j3pPIiTqKwZ1rKYx-fvDu9G1c/edit

**Comment by dzoladz** [comment]
@Walton485 Let me know if you need anything from me as you get started on the schedule grid
