### ISSUE TITLE
update header image on posters

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2020.alaoweb.org#87]
* still using the cod.png instead of the new wave header
* this should not have to be defined in every poster - the poster setup should do this in one place instead of having to define it on a case by case basis
  * (more broadly, I think we're doing too much in the default layout and should have more sub-layouts, but that's too big for this issue)

**Comment by dzoladz** [comment]
> (more broadly, I think we're doing too much in the default layout and should have more sub-layouts, but that's too big for this issue)

Let's bring this up at our next team meeting.
