### ISSUE TITLE
Need to Establish DNS Records in ALAOWEB Zone

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#9]
This has already been done for TEDSIG (see terminal output below).

We'll need a similar setup for the conference website.

CNAME Record:
2020.alaoweb.org  =>  alaoweb.github.io

```bash
➜  ~ nslookup tedsig.alaoweb.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
tedsig.alaoweb.org	canonical name = dzoladz.github.io.
Name:	dzoladz.github.io
Address: 185.199.111.153
Name:	dzoladz.github.io
Address: 185.199.108.153
Name:	dzoladz.github.io
Address: 185.199.109.153
Name:	dzoladz.github.io
Address: 185.199.110.153
```

**Comment by Nassaubound** [comment]
This has been completed:

nslookup 2020.alaoweb.github.io
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	2020.alaoweb.github.io
Address: 185.199.109.153
Name:	2020.alaoweb.github.io
Address: 185.199.108.153
Name:	2020.alaoweb.github.io
Address: 185.199.111.153
Name:	2020.alaoweb.github.io
Address: 185.199.110.153

**Comment by dzoladz** [comment]
Reopened from the terminal output above, but then realized that the CNAME was in place for `2020.alaoweb.org`.

```bash
➜  ~ nslookup 2020.alaoweb.org
Server:		192.168.1.51
Address:	192.168.1.51#53

Non-authoritative answer:
2020.alaoweb.org	canonical name = alaoweb.github.io.
Name:	alaoweb.github.io
Address: 185.199.111.153
Name:	alaoweb.github.io
Address: 185.199.109.153
Name:	alaoweb.github.io
Address: 185.199.110.153
Name:	alaoweb.github.io
Address: 185.199.108.153
```
Closing... and will add the CNAME record to the repo.
