### ISSUE TITLE
Minor Style Tweaks to Session-Search-Btn

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2020.alaoweb.org#98]
If anyone wants to take a stab at better positioning the `session-search-btn` on the schedule grid, especially through all of the breakpoints, assign yourself to this issue. We might also want to:

- [X] Provide some user feedback on btn hover

**Comment by dzoladz** [comment]
This vertical align could use adjustment as well

![Screen Shot 2020-07-02 at 10 14 46 AM](https://user-images.githubusercontent.com/10561752/86369931-15a72280-bc4d-11ea-9a6e-7e0bfbaa15a2.png)

**Comment by kenirwin** [comment]
Bootstrap `.btn` usually includes some standard :hover effects. It looks to me like the css for that is building ok, but that the .btn class has `background-color: #4285f4 !important`. And the `important` is overriding the hover. Not sure where the `important` is coming from

It looks to me like the relevant code for the hover is in `sass/vendor/bootstrap/mixin/_buttons.scss`:

```
&:hover,
  &:focus,
  &.focus,
  &:active,
  &.active,
  .open > &.dropdown-toggle {
    color: $color;
    background-color: darken($background, 10%);
        border-color: darken($border, 12%);
  }
```

which renders to `.btn-primary:hover { background-color: #286090}` (that's very much abbreviated) in main.css

**Comment by kenirwin** [comment]
May be able to override the !important with:
```
.btn-primary:hover {
    background-color: #286090 !important;
}
```

**Comment by dzoladz** [comment]
I've address another issue in your original PR and merged the code. Here's what remains:

- [ ] Select a more subtle color match for the schedule grid and session search buttons

**Comment by kenirwin** [comment]
I'd suggest that we come up with a color scheme we like for the "primary" and "secondary" bootstrap classes. We aren't using them much, but that seems like the way to go there.

**Comment by dzoladz** [comment]
Anything that we can do to make the color palette simple to understand and easily replicable across the site, I'm all for it. At the moment, we're using several different button colors without much thought placed into the semantics of color differences. Aside from the purely design perspective, It would be worthwhile for us to think about standardizing the semantics of our color decisions (i.e. using the same button color to identify the same button functionality, such as launching a zoom).

**Comment by dzoladz** [comment]
Alignment issues have been corrected and a color scheme has been implemented. Closing.
